<a href="https://colab.research.google.com/github/Kishan-25065638/data_science_wk1/blob/main/Tutorial3_25065638.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import numpy as np
import random as r

In [52]:
#tut-03.1

X=np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [54]:
#tut-03.2

Y=np.random.random((3,4))
print(Y)

[[0.19403369 0.35064562 0.91769305 0.96746247]
 [0.26437021 0.67791435 0.01333554 0.14217066]
 [0.78056533 0.46504654 0.04677483 0.03190946]]


In [55]:
#tut-03.3

A=np.zeros((3,3))
B=np.ones((3,3))
print(A,"\n","\n",B)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [56]:
#tut-03.4

C=np.random.random((6,3)) #original
print(C,"\n","\n")
print(C.T) #transposed

[[0.82668017 0.89674467 0.82836702]
 [0.92678081 0.10545171 0.22248825]
 [0.93153792 0.55045751 0.45024334]
 [0.88769991 0.15958086 0.83801463]
 [0.06523934 0.43791695 0.88348924]
 [0.89503241 0.29571416 0.00651515]] 
 

[[0.82668017 0.92678081 0.93153792 0.88769991 0.06523934 0.89503241]
 [0.89674467 0.10545171 0.55045751 0.15958086 0.43791695 0.29571416]
 [0.82836702 0.22248825 0.45024334 0.83801463 0.88348924 0.00651515]]


In [57]:
#tut-03.5

n=int(r.randint(1,10))
p=int(r.randint(1,10))
m=int(r.randint(1,10))

D=np.random.random((n,p))
E=np.random.random((p,m))
F=np.dot(D,E)

print(D,"\n","\n","\n",E,"\n","\n","\n",)
print("Dot Product: ","\n","\n","\n", F)


[[0.39633431 0.56341309 0.14318431 0.83704148]
 [0.46182616 0.52408917 0.39751133 0.10797719]
 [0.89994812 0.90098044 0.96370385 0.64741847]
 [0.5786048  0.32408298 0.41862155 0.70929315]
 [0.54430317 0.07266798 0.8690702  0.36320047]
 [0.93202249 0.07636247 0.05563956 0.91027289]] 
 
 
 [[0.93893769]
 [0.78037748]
 [0.83078341]
 [0.22664991]] 
 
 

Dot Product:  
 
 
 [[1.12047863]
 [1.19733221]
 [2.49546657]
 [1.30472598]
 [1.37210368]
 [1.18724029]]
